name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 22.3.0
          cache: 'npm'

      # Set environment variables and install dependencies
      - run: npm ci
        env:
          NODE_ENV: development

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # Run Nx commands
      - run: npx nx run ph-balanced:lint
      - run: npx nx run ph-balanced:test
      - run: npx nx run ph-balanced:e2e-ci
      - run: npx nx run ph-balanced:build:production

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your AWS region

      # Upload files to S3
      - name: Upload to S3
        run: |
          aws s3 sync ./dist/ph-balanced s3://ph-balanced.com/ --delete
