name: CI

on:
  release:
    types:
      - created

permissions:
  actions: read
  contents: read

jobs:
  main:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: Production
    steps:
      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 22.3.0
          cache: 'npm'

      # This should really go into a separate command, then environments for non-prod prod
      # But, because this is just me pushing out to one space - going to change this in the future.
      - run: |
          echo "NODE_ENV=development" >> $GITHUB_ENV
          npm ci

      - run: npm install -g @nrwl/cli

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js"

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      - name: Run Linter
        run: npx nx affected:lint --base=main --stop-agents-after=120
      - name: Run Tests
        run: npx nx affected:test --base=main --stop-agents-after=120
      - name: Run E2E
        run: npx nx affected --base=main --parallel 1 -t e2e-ci --stop-agents-after=120
      - name: Build
        run: npx nx run ph-balanced:build:production
        env:
          NODE_ENV: production

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your AWS region

      # Upload files to S3
      - name: Upload to S3
        run: |
          aws s3 sync ./dist/ph-balanced s3://ph-balanced.com/ --delete
